spring:
  application:
    name: spring-api-starter
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: bikram123@

  jpa:
    show-sql: true

